/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BaliItineraryRouteImport } from './routes/bali-itinerary'
import { Route as EuropeItineraryRouteImport } from './routes/europe-itinerary'
import { Route as JapanItineraryRouteImport } from './routes/japan-itinerary'
import { Route as MalaysiaItineraryRouteImport } from './routes/malaysia-itinerary'
import { Route as SingaporeCruiseItineraryRouteImport } from './routes/singapore-cruise-itinerary'
import { Route as SingaporeItineraryRouteImport } from './routes/singapore-itinerary'
import { Route as ThailandItineraryRouteImport } from './routes/thailand-itinerary'
import { Route as VietnamItineraryRouteImport } from './routes/vietnam-itinerary'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BaliItineraryRoute = BaliItineraryRouteImport.update({
  id: '/bali-itinerary',
  path: '/bali-itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const EuropeItineraryRoute = EuropeItineraryRouteImport.update({
  id: '/europe-itinerary',
  path: '/europe-itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const JapanItineraryRoute = JapanItineraryRouteImport.update({
  id: '/japan-itinerary',
  path: '/japan-itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const MalaysiaItineraryRoute = MalaysiaItineraryRouteImport.update({
  id: '/malaysia-itinerary',
  path: '/malaysia-itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const SingaporeCruiseItineraryRoute =
  SingaporeCruiseItineraryRouteImport.update({
    id: '/singapore-cruise-itinerary',
    path: '/singapore-cruise-itinerary',
    getParentRoute: () => rootRouteImport,
  } as any)
const SingaporeItineraryRoute = SingaporeItineraryRouteImport.update({
  id: '/singapore-itinerary',
  path: '/singapore-itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const ThailandItineraryRoute = ThailandItineraryRouteImport.update({
  id: '/thailand-itinerary',
  path: '/thailand-itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const VietnamItineraryRoute = VietnamItineraryRouteImport.update({
  id: '/vietnam-itinerary',
  path: '/vietnam-itinerary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bali-itinerary': typeof BaliItineraryRoute
  '/europe-itinerary': typeof EuropeItineraryRoute
  '/japan-itinerary': typeof JapanItineraryRoute
  '/malaysia-itinerary': typeof MalaysiaItineraryRoute
  '/singapore-cruise-itinerary': typeof SingaporeCruiseItineraryRoute
  '/singapore-itinerary': typeof SingaporeItineraryRoute
  '/thailand-itinerary': typeof ThailandItineraryRoute
  '/vietnam-itinerary': typeof VietnamItineraryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bali-itinerary': typeof BaliItineraryRoute
  '/europe-itinerary': typeof EuropeItineraryRoute
  '/japan-itinerary': typeof JapanItineraryRoute
  '/malaysia-itinerary': typeof MalaysiaItineraryRoute
  '/singapore-cruise-itinerary': typeof SingaporeCruiseItineraryRoute
  '/singapore-itinerary': typeof SingaporeItineraryRoute
  '/thailand-itinerary': typeof ThailandItineraryRoute
  '/vietnam-itinerary': typeof VietnamItineraryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bali-itinerary': typeof BaliItineraryRoute
  '/europe-itinerary': typeof EuropeItineraryRoute
  '/japan-itinerary': typeof JapanItineraryRoute
  '/malaysia-itinerary': typeof MalaysiaItineraryRoute
  '/singapore-cruise-itinerary': typeof SingaporeCruiseItineraryRoute
  '/singapore-itinerary': typeof SingaporeItineraryRoute
  '/thailand-itinerary': typeof ThailandItineraryRoute
  '/vietnam-itinerary': typeof VietnamItineraryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bali-itinerary'
    | '/europe-itinerary'
    | '/japan-itinerary'
    | '/malaysia-itinerary'
    | '/singapore-cruise-itinerary'
    | '/singapore-itinerary'
    | '/thailand-itinerary'
    | '/vietnam-itinerary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bali-itinerary'
    | '/europe-itinerary'
    | '/japan-itinerary'
    | '/malaysia-itinerary'
    | '/singapore-cruise-itinerary'
    | '/singapore-itinerary'
    | '/thailand-itinerary'
    | '/vietnam-itinerary'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bali-itinerary'
    | '/europe-itinerary'
    | '/japan-itinerary'
    | '/malaysia-itinerary'
    | '/singapore-cruise-itinerary'
    | '/singapore-itinerary'
    | '/thailand-itinerary'
    | '/vietnam-itinerary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BaliItineraryRoute: typeof BaliItineraryRoute
  EuropeItineraryRoute: typeof EuropeItineraryRoute
  JapanItineraryRoute: typeof JapanItineraryRoute
  MalaysiaItineraryRoute: typeof MalaysiaItineraryRoute
  SingaporeCruiseItineraryRoute: typeof SingaporeCruiseItineraryRoute
  SingaporeItineraryRoute: typeof SingaporeItineraryRoute
  ThailandItineraryRoute: typeof ThailandItineraryRoute
  VietnamItineraryRoute: typeof VietnamItineraryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bali-itinerary': {
      id: '/bali-itinerary'
      path: '/bali-itinerary'
      fullPath: '/bali-itinerary'
      preLoaderRoute: typeof BaliItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/europe-itinerary': {
      id: '/europe-itinerary'
      path: '/europe-itinerary'
      fullPath: '/europe-itinerary'
      preLoaderRoute: typeof EuropeItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/japan-itinerary': {
      id: '/japan-itinerary'
      path: '/japan-itinerary'
      fullPath: '/japan-itinerary'
      preLoaderRoute: typeof JapanItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/malaysia-itinerary': {
      id: '/malaysia-itinerary'
      path: '/malaysia-itinerary'
      fullPath: '/malaysia-itinerary'
      preLoaderRoute: typeof MalaysiaItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/singapore-cruise-itinerary': {
      id: '/singapore-cruise-itinerary'
      path: '/singapore-cruise-itinerary'
      fullPath: '/singapore-cruise-itinerary'
      preLoaderRoute: typeof SingaporeCruiseItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/singapore-itinerary': {
      id: '/singapore-itinerary'
      path: '/singapore-itinerary'
      fullPath: '/singapore-itinerary'
      preLoaderRoute: typeof SingaporeItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thailand-itinerary': {
      id: '/thailand-itinerary'
      path: '/thailand-itinerary'
      fullPath: '/thailand-itinerary'
      preLoaderRoute: typeof ThailandItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vietnam-itinerary': {
      id: '/vietnam-itinerary'
      path: '/vietnam-itinerary'
      fullPath: '/vietnam-itinerary'
      preLoaderRoute: typeof VietnamItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BaliItineraryRoute: BaliItineraryRoute,
  EuropeItineraryRoute: EuropeItineraryRoute,
  JapanItineraryRoute: JapanItineraryRoute,
  MalaysiaItineraryRoute: MalaysiaItineraryRoute,
  SingaporeCruiseItineraryRoute: SingaporeCruiseItineraryRoute,
  SingaporeItineraryRoute: SingaporeItineraryRoute,
  ThailandItineraryRoute: ThailandItineraryRoute,
  VietnamItineraryRoute: VietnamItineraryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
